<a href="https://colab.research.google.com/github/esubalewmilam-hue/MIS433/blob/main/Week3Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment - Analyzing the IMDB Top 1000 Movies

In this assignment, you will be working with this dataset of IMDB top 1000 movies.

Source: https://www.kaggle.com/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows

In [ ]:
import pandas as pd
import numpy as np

To read the data file from your Google Drive, mount your drive first.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Read the data file "imdb_top_1000.csv" to a dataframe named "imdb"
imdb = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/imdb_top_1000.csv', header=0)
imdb.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [ ]:
# Describe the dataframe using the info() method.
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

In [ ]:
# List all the column names:
imdb.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

## Part 1: Data Manipulation

In [ ]:
# Display Series_Title, Released_Year, and IMDB_Rating of the top 10 movies.
imdb[['Series_Title', 'Released_Year', 'IMDB_Rating']].head(10)

                                    Series_Title Released_Year  IMDB_Rating
0                       The Shawshank Redemption          1994          9.3
1                                  The Godfather          1972          9.2
2                                The Dark Knight          2008          9.0
3                         The Godfather: Part II          1974          9.0
4                                   12 Angry Men          1957          9.0
5  The Lord of the Rings: The Return of the King          2003          8.9
6                                   Pulp Fiction          1994          8.9
7                               Schindler's List          1993          8.9
8                                      Inception          2010          8.8
9                                     Fight Club          1999          8.8

In [ ]:
# Display movies ranked 11-20.
# Show their Series_Title, Released_Year, and IMDB_Rating.
imdb[['Series_Title', 'Released_Year', 'IMDB_Rating']].iloc[10:20]

,Series_Title,Released_Year,IMDB_Rating
10,The Lord of the Rings: The Fellowship of the Ring,2001,8.8
11,Forrest Gump,1994,8.8
12,"Il buono, il brutto, il cattivo",1966,8.8
13,The Lord of the Rings: The Two Towers,2002,8.7
14,The Matrix,1999,8.7
15,Goodfellas,1990,8.7
16,Star Wars: Episode V - The Empire Strikes Back,1980,8.7
17,One Flew Over the Cuckoo's Nest,1975,8.7
18,Hamilton,2020,8.6
19,Gisaengchung,2019,8.6

In [ ]:
# Select all movies directed by Quentin Tarantino.
# Show their Series_Title, Released_Year, IMDB_Rating, and Gross.
imdb.loc[imdb['Director'] == 'Quentin Tarantino', ['Series_Title', 'Released_Year', 'IMDB_Rating', 'Gross']]

                         Series_Title Released_Year  IMDB_Rating        Gross
6                        Pulp Fiction          1994          8.9  107,928,762
62                   Django Unchained          2012          8.4  162,805,434
93               Inglourious Basterds          2009          8.3  120,540,719
103                    Reservoir Dogs          1992          8.3    2,832,029
241                 Kill Bill: Vol. 1          2003          8.1   70,099,045
369                 Kill Bill: Vol. 2          2004          8.0   66,208,183
584                 The Hateful Eight          2015          7.8   54,117,416
879  Once Upon a Time... in Hollywood          2019          7.6  142,502,728

In [ ]:
# Select all R rated movies with IMDB_Rating>=8.5
# Show their Series_Title, Released_Year, Certificate, and IMDB_Rating.
imdb.loc[(imdb['Certificate'] == 'R') & (imdb['IMDB_Rating'] >= 8.5), ['Series_Title', 'Released_Year', 'Certificate', 'IMDB_Rating']]

           Series_Title Released_Year Certificate  IMDB_Rating
24  Saving Private Ryan          1998           R          8.6
38          The Pianist          2002           R          8.5
40   American History X          1998           R          8.5

In [ ]:
# How many unique values are there in the column "Released_Year"?
# Hint: nunique()
imdb['Released_Year'].nunique()

100

In [ ]:
# Count the number of movies in each "Released_Year".
# Hint: value_counts()
imdb['Released_Year'].value_counts()

Released_Year
2014    32
2004    31
2009    29
2013    28
2016    28
        ..
1920     1
1930     1
1922     1
1943     1
PG       1
Name: count, Length: 100, dtype: int64

In [ ]:
# In this dataset, there is a movie with an error in "Released_Year".
# Hint: Released_Year should be a 4-digit integer but this movie's year is not.
# Find this movie.
imdb[imdb.Released_Year=="PG"]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,PG,U,140 min,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,77.0,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,"173,837,933"

In [ ]:
# Correct the values for the corresponding columns ("Released_Year" and "Certificate").
# You may want to look up this movie on www.imdb.com.
# Hint: You can set value for a particular row by: df.loc[row_index, column_name] = new_value
imdb.loc[966, 'Released_Year'] = '1995'
imdb.loc[966, 'Certificate'] = 'PG'

In [ ]:
# Change the data type of "Released_Year" to int
imdb['Released_Year'] = imdb['Released_Year'].replace('PG', '1995').astype(int)

In [ ]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their Series_Title, Released_Year, Certificate, and IMDB_Rating.
imdb.loc[
    (imdb['Released_Year'] >= 2010) & (imdb['IMDB_Rating'] >= 8.5),['Series_Title', 'Released_Year', 'Certificate', 'IMDB_Rating']
]

        Series_Title  Released_Year Certificate  IMDB_Rating
8          Inception           2010          UA          8.8
18          Hamilton           2020       PG-13          8.6
19      Gisaengchung           2019           A          8.6
20   Soorarai Pottru           2020           U          8.6
21      Interstellar           2014          UA          8.6
33             Joker           2019           A          8.5
34          Whiplash           2014           A          8.5
35  The Intouchables           2011          UA          8.5

In [ ]:
# Select all movies whose genres contain 'Animation'
imdb[imdb['Genre'].str.contains('Animation', na=False)]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
23,https://m.media-amazon.com/images/M/MV5BMjlmZm...,Sen to Chihiro no kamikakushi,2001,U,125 min,"Animation, Adventure, Family",8.6,"During her family's move to the suburbs, a sul...",96.0,Hayao Miyazaki,Daveigh Chase,Suzanne Pleshette,Miyu Irino,Rumi Hiiragi,651376,"10,055,859"
43,https://m.media-amazon.com/images/M/MV5BYTYxNG...,The Lion King,1994,U,88 min,"Animation, Adventure, Drama",8.5,Lion prince Simba and his father are targeted ...,88.0,Roger Allers,Rob Minkoff,Matthew Broderick,Jeremy Irons,James Earl Jones,942045,"422,783,777"
46,https://m.media-amazon.com/images/M/MV5BZmY2Nj...,Hotaru no haka,1988,U,89 min,"Animation, Drama, War",8.5,A young boy and his little sister struggle to ...,94.0,Isao Takahata,Tsutomu Tatsumi,Ayano Shiraishi,Akemi Yamaguchi,Yoshiko Shinohara,235231,NaN
56,https://m.media-amazon.com/images/M/MV5BODRmZD...,Kimi no na wa.,2016,U,106 min,"Animation, Drama, Fantasy",8.4,Two strangers find themselves linked in a biza...,79.0,Makoto Shinkai,Ryûnosuke Kamiki,Mone Kamishiraishi,Ryô Narita,Aoi Yûki,194838,"5,017,246"
58,https://m.media-amazon.com/images/M/MV5BMjMwND...,Spider-Man: Into the Spider-Verse,2018,U,117 min,"Animation, Action, Adventure",8.4,Teen Miles Morales becomes the Spider-Man of h...,87.0,Bob Persichetti,Peter Ramsey,Rodney Rothman,Shameik Moore,Jake Johnson,375110,"190,241,310"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
956,https://m.media-amazon.com/images/M/MV5BODkxNG...,Mulan,1998,U,88 min,"Animation, Adventure, Family",7.6,"To save her father from death in the army, a y...",71.0,Tony Bancroft,Barry Cook,Ming-Na Wen,Eddie Murphy,BD Wong,256906,"120,620,254"
971,https://m.media-amazon.com/images/M/MV5BMTY5Nj...,Omohide poro poro,1991,U,118 min,"Animation, Drama, Romance",7.6,A twenty-seven-year-old office worker travels ...,90.0,Isao Takahata,Miki Imai,Toshirô Yanagiba,Yoko Honna,Mayumi Izuka,27071,"453,243"
976,https://m.media-amazon.com/images/M/MV5BN2JlZT...,The Little Mermaid,1989,U,83 min,"Animation, Family, Fantasy",7.6,A mermaid princess makes a Faustian bargain in...,88.0,Ron Clements,John Musker,Jodi Benson,Samuel E. Wright,Rene Auberjonois,237696,"111,543,479"
986,https://m.media-amazon.com/images/M/MV5BMzZiOD...,Watership Down,1978,U,91 min,"Animation, Adventure, Drama",7.6,Hoping to escape destruction by human develope...,64.0,Martin Rosen,John Hubley,John Hurt,Richard Briers,Ralph Richardson,33656,NaN
992,https://m.media-amazon.com/images/M/MV5BMjAwMT...,The Jungle Book,1967,U,78 min,"Animation, Adventure, Family",7.6,Bagheera the Panther and Baloo the Bear have a...,65.0,Wolfgang Reitherman,Phil Harris,Sebastian Cabot,Louis Prima,Bruce Reitherman,166409,"141,843,612"

In [ ]:
# Create a new dataframe called "stars" including the following columns:
# Series_Title, Released_Year, Star1, Star2, Star3, Star4
stars = imdb[['Series_Title', 'Released_Year', 'Star1', 'Star2', 'Star3', 'Star4']].copy()
stars

,Series_Title,Released_Year,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,1994,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,The Godfather,1972,Marlon Brando,Al Pacino,James Caan,Diane Keaton
2,The Dark Knight,2008,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine
3,The Godfather: Part II,1974,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton
4,12 Angry Men,1957,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler
...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen
996,Giant,1956,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker
997,From Here to Eternity,1953,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed
998,Lifeboat,1944,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix
999,The 39 Steps,1935,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle

In [ ]:
# Create a new dataframe called "genres" including the following columns:
# Series_Title, Released_Year, Genre.
genres = imdb[['Series_Title', 'Released_Year', 'Genre']].copy()
genres

                 Series_Title  Released_Year                     Genre
0    The Shawshank Redemption           1994                     Drama
1               The Godfather           1972              Crime, Drama
2             The Dark Knight           2008      Action, Crime, Drama
3      The Godfather: Part II           1974              Crime, Drama
4                12 Angry Men           1957              Crime, Drama
..                        ...            ...                       ...
995    Breakfast at Tiffany's           1961    Comedy, Drama, Romance
996                     Giant           1956            Drama, Western
997     From Here to Eternity           1953       Drama, Romance, War
998                  Lifeboat           1944                Drama, War
999              The 39 Steps           1935  Crime, Mystery, Thriller

[1000 rows x 3 columns]

In [ ]:
# Sorting:
# Sort the genres dataframe in ascending order of "Released_Year"
genres = genres.sort_values('Released_Year')
genres

                     Series_Title  Released_Year                         Genre
321  Das Cabinet des Dr. Caligari           1920      Fantasy, Horror, Mystery
127                       The Kid           1921         Comedy, Drama, Family
568                     Nosferatu           1922               Fantasy, Horror
194                  Sherlock Jr.           1924       Action, Comedy, Romance
193                 The Gold Rush           1925      Adventure, Comedy, Drama
..                            ...            ...                           ...
612    The Trial of the Chicago 7           2020      Drama, History, Thriller
613                          Druk           2020                 Comedy, Drama
20                Soorarai Pottru           2020                         Drama
18                       Hamilton           2020     Biography, Drama, History
205                          Soul           2020  Animation, Adventure, Comedy

[1000 rows x 3 columns]

In [ ]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their Series_Title, Released_Year, Certificate, and Gross.
# Sort them in descending order of "Gross"
imdb.loc[(imdb['Released_Year'] >= 2010) & (imdb['IMDB_Rating'] >= 8.5), ['Series_Title', 'Released_Year', 'Certificate', 'Gross']].sort_values('Gross', ascending=False)

        Series_Title  Released_Year Certificate        Gross
19      Gisaengchung           2019           A   53,367,844
33             Joker           2019           A  335,451,311
8          Inception           2010          UA  292,576,195
21      Interstellar           2014          UA  188,020,017
35  The Intouchables           2011          UA   13,182,281
34          Whiplash           2014           A   13,092,000
18          Hamilton           2020       PG-13          NaN
20   Soorarai Pottru           2020           U          NaN

In [ ]:
# Does the sorting result look right to you? What's the problem? Gross is stored as text containing commas, so it sorts alphabetically instead of numerically.

In [ ]:
# Resolve this problem of "Gross" and convert its data type to float
# Hint: You may find this webpage useful:
# https://stackoverflow.com/questions/28986489/how-to-replace-text-in-a-column-of-a-pandas-dataframe
imdb['Gross'] = imdb['Gross'].str.replace(',', '', regex=False).astype(float)

In [ ]:
# Next, redo the sorting on Gross

# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their Series_Title, Released_Year, Certificate, and Gross.
# Sort them in descending order of "Gross"
imdb.loc[(imdb['Released_Year'] >= 2010) & (imdb['IMDB_Rating'] >= 8.5), ['Series_Title', 'Released_Year', 'Certificate', 'Gross']].sort_values('Gross', ascending=False)

        Series_Title  Released_Year Certificate        Gross
33             Joker           2019           A  335451311.0
8          Inception           2010          UA  292576195.0
21      Interstellar           2014          UA  188020017.0
19      Gisaengchung           2019           A   53367844.0
35  The Intouchables           2011          UA   13182281.0
34          Whiplash           2014           A   13092000.0
18          Hamilton           2020       PG-13          NaN
20   Soorarai Pottru           2020           U          NaN

In [ ]:
# Add a new column "Runtime_min" by removing the substring " min" in "Runtime"
# Set its data type as int
# Hint: https://stackoverflow.com/questions/36505847/substring-of-an-entire-column-in-pandas-dataframe
imdb['Runtime_min'] = imdb['Runtime'].str.replace(' min', '', regex=False).astype(int)

In [ ]:
# Add a new column "Age_Years" by the expression: Current year - Released_Year chatgpt assisted
from datetime import datetime
imdb['Age_Years'] = datetime.now().year - imdb['Released_Year']

In [ ]:
# Add a new column "Decade" with values as 1980, 1990, 2000, 2010, 2020, etc.
imdb['Decade'] = (imdb['Released_Year'] // 10) * 10

## Part 2: Data Summarization

In [ ]:
# Total "Gross" of all top 1000 movies
imdb['Gross'].sum()

np.float64(56536877976.0)

In [ ]:
# Average "No_of_Votes" of all movies
imdb['No_of_Votes'].mean()

np.float64(273692.911)

In [ ]:
# Count movies in each decade (e.g., ..., 1980, 1990, 2000, 2010, 2020)
# Sort decades by the number of movies in descending order
imdb['Decade'] = (imdb['Released_Year'] // 10) * 10

imdb['Decade'].value_counts().to_frame(name='Movie_Count')

        Movie_Count
Decade
2010            242
2000            237
1990            151
1980             89
1970             76
1960             73
1950             56
1940             35
1930             24
1920             11
2020              6

In [ ]:
# Count movies by different directors.
# Show the top 10 directors with the most movies in this list
imdb['Director'].value_counts().head(10).to_frame(name='Movie_Count')

                   Movie_Count
Director
Alfred Hitchcock            14
Steven Spielberg            13
Hayao Miyazaki              11
Akira Kurosawa              10
Martin Scorsese             10
Woody Allen                  9
Stanley Kubrick              9
Billy Wilder                 9
Clint Eastwood               8
Christopher Nolan            8

In [ ]:
# For each director, calculate the number of movies, average IMDB_Rating, and total gross.
# Rank them in descending order of total gross
# Show the top 10 directors with the highest total gross
director_summary = imdb.groupby('Director').agg(
    Movie_Count=('Series_Title', 'count'),
    Average_IMDB_Rating=('IMDB_Rating', 'mean'),
    Total_Gross=('Gross', 'sum')
).reset_index()

director_summary.sort_values('Total_Gross', ascending=False).head(10)

              Director  Movie_Count  Average_IMDB_Rating   Total_Gross
470   Steven Spielberg           13             8.030769  2.478133e+09
36       Anthony Russo            4             8.075000  2.205039e+09
83   Christopher Nolan            8             8.462500  1.937454e+09
202      James Cameron            5             8.080000  1.748237e+09
383      Peter Jackson            5             8.400000  1.597312e+09
195        J.J. Abrams            3             7.833333  1.423171e+09
58           Brad Bird            4             7.900000  1.099628e+09
426    Robert Zemeckis            5             8.120000  1.049446e+09
107        David Yates            3             7.800000  9.789537e+08
380        Pete Docter            4             8.125000  9.393821e+08

In [ ]:
# Group movies by decade and director
# In each group (i.e., for each decade and each director),
# calculate the number of movies and average IMDB rating.
# Sort in descending order of movie count
decade_director_summary = imdb.groupby(['Decade', 'Director']).agg(
    Movie_Count=('Series_Title', 'count'),
    Average_IMDB_Rating=('IMDB_Rating', 'mean')
).reset_index()

decade_director_summary.sort_values('Movie_Count', ascending=False)

     Decade              Director  Movie_Count  Average_IMDB_Rating
51     1950          Billy Wilder            6             8.133333
47     1950        Akira Kurosawa            5             8.260000
598    2010      Denis Villeneuve            5             7.980000
50     1950      Alfred Hitchcock            5             8.220000
240    1980      Steven Spielberg            5             7.980000
..      ...                   ...          ...                  ...
733    2010          Tyler Nilson            1             7.600000
734    2010          Umesh Shukla            1             8.100000
735    2010            Vikas Bahl            1             8.200000
736    2010  Vikramaditya Motwane            1             8.200000
737    2010       Vishal Bhardwaj            1             8.100000

[749 rows x 4 columns]

In [ ]:
# Find the top 3 highest rated movies of each year since 2010.
# Show their released year, ranking, title, and IMDB_Rating.
# Sort them in descending order of year and ascending order of ranking
#chatgpt created
top_movies_by_year = imdb.loc[
    imdb['Released_Year'] >= 2010,
    ['Released_Year', 'Series_Title', 'IMDB_Rating']
].copy()

top_movies_by_year['Ranking'] = top_movies_by_year.groupby(
    'Released_Year'
)['IMDB_Rating'].rank(method='first', ascending=False)

top_movies_by_year['Ranking'] = top_movies_by_year['Ranking'].astype(int)

top_movies_by_year = top_movies_by_year.loc[
    top_movies_by_year['Ranking'] <= 3,
    ['Released_Year', 'Ranking', 'Series_Title', 'IMDB_Rating']
].sort_values(['Released_Year', 'Ranking'], ascending=[False, True])

top_movies_by_year

     Released_Year  Ranking                       Series_Title  IMDB_Rating
18            2020        1                           Hamilton          8.6
20            2020        2                    Soorarai Pottru          8.6
205           2020        3                               Soul          8.1
19            2019        1                       Gisaengchung          8.6
33            2019        2                              Joker          8.5
59            2019        3                  Avengers: Endgame          8.4
53            2018        1                         Capharnaüm          8.4
58            2018        2  Spider-Man: Into the Spider-Verse          8.4
60            2018        3             Avengers: Infinity War          8.4
54            2017        1          Ayla: The Daughter of War          8.4
55            2017        2                       Vikram Vedha          8.4
61            2017        3                               Coco          8.4
56            2016        1                     Kimi no na wa.          8.4
57            2016        2                             Dangal          8.4
196           2016        3                               Pink          8.1
133           2015        1                             Talvar          8.2
136           2015        2                           Drishyam          8.2
203           2015        3                               Room          8.1
21            2014        1                       Interstellar          8.6
34            2014        2                           Whiplash          8.5
200           2014        3                              Mommy          8.1
87            2013        1                           Drishyam          8.3
137           2013        2                              Queen          8.2
138           2013        3                        Mandariinid          8.2
62            2012        1                   Django Unchained          8.4
63            2012        2              The Dark Knight Rises          8.4
88            2012        3                             Jagten          8.3
35            2011        1                   The Intouchables          8.5
89            2011        2            Jodaeiye Nader az Simin          8.3
144           2011        3                            Warrior          8.2
8             2010        1                          Inception          8.8
90            2010        2                          Incendies          8.3
141           2010        3                              Udaan          8.2

In [ ]:
# Find all directors whose movies appeared in at least five different decades.
# Your result should include: director, decade, and the number of movies in the decade.
director_decades = imdb.groupby(['Director', 'Decade']).agg(
    Movie_Count=('Series_Title', 'count')
).reset_index()

director_decades = director_decades[
    director_decades.groupby('Director')['Decade'].transform('nunique') >= 5
].sort_values(['Director', 'Decade'])

director_decades

             Director  Decade  Movie_Count
247    Hayao Miyazaki    1970            1
248    Hayao Miyazaki    1980            4
249    Hayao Miyazaki    1990            2
250    Hayao Miyazaki    2000            3
251    Hayao Miyazaki    2010            1
424   Martin Scorsese    1970            1
425   Martin Scorsese    1980            3
426   Martin Scorsese    1990            2
427   Martin Scorsese    2000            1
428   Martin Scorsese    2010            3
644  Steven Spielberg    1970            2
645  Steven Spielberg    1980            5
646  Steven Spielberg    1990            3
647  Steven Spielberg    2000            2
648  Steven Spielberg    2010            1

In [ ]:
# Ask two questions about this dataset and write your code to answer them.
# Question 1: Do movies with more votes tend to have higher ratings?
imdb['No_of_Votes'].corr(imdb['IMDB_Rating'])

np.float64(0.494978835862142)

In [ ]:
# Question 2: Which movies have high IMDb ratings but low Metascores?
high_rating_low_metascore = imdb.loc[
    (imdb['IMDB_Rating'] >= 8.0) & (imdb['Meta_score'] < 60),
    ['Series_Title', 'IMDB_Rating', 'Meta_score']
].sort_values(
    ['IMDB_Rating', 'Meta_score'],
    ascending=[False, True]
)

high_rating_low_metascore

                                   Series_Title  IMDB_Rating  Meta_score
26                              La vita è bella          8.6        59.0
35                             The Intouchables          8.5        57.0
33                                        Joker          8.5        59.0
96                                       Snatch          8.3        55.0
109  Star Wars: Episode VI - Return of the Jedi          8.3        58.0
272                        Pink Floyd: The Wall          8.1        47.0
271                                   The Thing          8.1        57.0
249        La leggenda del pianista sull'oceano          8.1        58.0
356                              Tropa de Elite          8.0        33.0
397                              Bound by Honor          8.0        47.0
342                           Bohemian Rhapsody          8.0        49.0
352                             My Name Is Khan          8.0        50.0
374                               Kal Ho Naa Ho          8.0        54.0
377                                    Big Fish          8.0        58.0
418                                    Papillon          8.0        58.0
351                                     Yip Man          8.0        59.0
398                            Scent of a Woman          8.0        59.0